### ISSUE TITLE
Docker Images Not Available

### ISSUE THREAD

**Issue by ch92st** [tarfeef101/omada_controller_docker#2]
Hi  There,

Few days ago the omada controller went offline (On Docker).
Seems that the image is no longer available.

I cannot migrate the current controller to a new one

Could you please inform me if this issue is from your side?

**Comment by tarfeef101** [comment]
I can try and repush later today. Haven't built from newer controller versions because they broke compatibility and haven't had time to deal with that. Should be able to publish the old build though

**Comment by ch92st** [comment]
Hi,

If you can push the image just to be able to migrate to a new controller or take a backup of the site to deploy it to omada cloud controller will be appreciated.

Thank you in advance.



Best Regards,

Christos Stylianou



T: +357 99243110 |  E: ***@***.******@***.***>

________________________________

🌳Please consider the environment. Do you really need to print this email?

________________________________



________________________________

**Comment by ch92st** [comment]
Hi,

Any update please?

**Comment by tarfeef101** [comment]
images should be back on docker hub

**Comment by ch92st** [comment]
Cannot see the image on docker hub. Also still cannot access my controller

**Comment by tarfeef101** [comment]
https://hub.docker.com/r/tarfeef101/omada_controller/tags

they're right there...

**Comment by ch92st** [comment]
Do you have any idea how can I access the my controller after you publish the image?
I am not so familiar with docker :/

**Comment by tarfeef101** [comment]
Sorry, this is really more of a place to report technical issues with the code, not so much a tech support forum :sweat_smile: 

[this](https://docs.docker.com/compose/intro/compose-application-model/) is probably a good place to start with docker-compose learning.

**Comment by ch92st** [comment]
I mean do you know if needed any kind of rebuild of the controller after you publish the image?

**Comment by tarfeef101** [comment]
the image IS the build of the controller, all you do is run it...

**Comment by ch92st** [comment]
Okay, I am asking because since you removed the image the controller went offline and cannot access it. If I run your image it will create a new controller..

**Comment by tarfeef101** [comment]
I'm not sure what your deployment environment looks like, but images are basically big files that define "what to run". When you deploy, those are downloaded, stored on the machine, and run. The runtime object is a `container`. Docker Hub removing the images does not translate to your container stopping, nor should it delete the image from the machine running that container. 

If your issue is that the container stopped, simply running `docker compose up -d` again should bring it back up. If there's an error, I suspect it's that it was not shut down gracefully, and there is a mongoDB lock file you need to delete to allow it to continue working. you'd need to check the container logs for that. 

figuring all that out is a bit outside the scope of what I'm able to provide here, though. this is a simple tool i made to make my life easier managing my controller, which I shared with the world in case anyone else wanted to do things the same way. not paid software with enterprise support :sweat_smile:

**Comment by ch92st** [comment]
Thank you very much
